sudo: true
language: java
script:
  - mvn install
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
before_install: 
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo add-apt-repository ppa:rwky/nodejs -y
  - sudo apt-get update -qq 
  - sudo apt-get install -qq python3.4
  - sudo apt-get install -qq nodejs
  